# This is a basic workflow to help you get started with Actions
#VERSION 2
#renew
name: Docker image sync to ACR
env:
  REGISTRY_URL: "21vrepo.azurecr.cn/devopsvip"
on:
  push:
    paths:
      - 'images.json'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Run Push Docker images
      run: |
        mkdir -p images/ 
        python uploader.py ${{ secrets.ACR_USERNAME}} ${{ secrets.ACR_PASSWD}} ${REGISTRY_URL}
    - uses: actions/upload-artifact@v4
      with: 
        name: docker-image
        path: images/*
